### ISSUE TITLE
Sprite / hatching orientation when the map bearing is changed

### ISSUE THREAD

**Issue by fxi** [unep-grid/mapx#995]
Currently, when rotating the map, the rule’s hatching is not oriented correctly, leading to incorrect readings. A solution would be to update a CSS variable --mx_map_rotation to align the hatching properly with the map’s rotation.

```js
map.on('rotate', () => {
    const bearing = map.getBearing();
    document.body.style.setProperty('--mx_map_rotation', `${bearing}deg`);
});
```

```css
.mx-legend-vt-rule-background {
    transform: rotate(var(--mx_map_rotation));
}
```

https://github.com/unep-grid/mapx/assets/1196833/d2695e4b-3c54-40ee-85f2-865318fac9eb
